trigger:
- master
- release/*

phases:
- phase: Windows
  queue:
    name: Hosted VS2017
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: 2.1.403
  - template: /eng/common/templates/steps/helix-publish.yml
    parameters:
      HelixSource: pr/your/helix/source # sources must start with pr/, official/, prodcon/, or agent/
      HelixType: type/tests
      # HelixBuild: $(Build.BuildNumber) -- This property is set by default
      HelixTargetQueues: Windows.10.Amd64.Open;Windows.7.Amd64.Open
      HelixAccessToken: $(BotAccount-dotnet-github-anon-kaonashi-bot-helix-token)
      # HelixPreCommands: echo pre
      # HelixPostCommands: echo post
      WorkItemDirectory: $(Build.SourcesDirectory)
      WorkItemCommand: echo hai
      EnableXUnitReporter: true # required for reporting out XUnit test results
      # WaitForWorkItemCompletion: true -- defaults to true
      IncludeDotNetCli: true
      DotNetCliPackageType: sdk
      DotNetCliVersion: 2.1.3
